<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="./css/style.css" type="text/css" />
    <title>Accueil 3WA Tasks</title>
</head>
<body>

    <h1>3WA Tasks</h1>

    <div>
        <h2>The best way to optimize your time</h2>
    </div>

    <div>
        <p>Based on the Eisenhower method, our application give you the best order to do what you have to do.</p>
    </div>

    <div>
       <a href="register.php">Register</a>
       <a href="login.php">Login</a>
    </div>

</body>
</html>