<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Accueil</title>
    <link rel="stylesheet" href="./css/style.css" type="text/css" />
</head>
<body>

    <header>
        <a href="index.php">3WA Tasks</a>
    </header>

    <main>
        <div class="container">
            <h1>3WA Tasks</h1>

            <div>
                <h2>The best way to optimize your time</h2>
            </div>

            <div>
                <p>Based on the Eisenhower method, our application give you the best order to do what you have to do</p>
            </div>

            <div>
                <a href="register.php">Register</a>
                <a href="login.php">Login</a>
            </div>
        </div>
    </main>

    <footer>
        <p>©2024 - 3W Academy</p>
    </footer>
</body>
</html>