<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    
    <title>Accueil 3WA Tasks</title>
</head>
<body>
    
    <h1>3WA Tasks</h1>
    <div>
        <h2>The best way to optimize your time</h2>
    </div>
    
    <div>
        <p>Based on the Eisenhower method, our application give you the best order to do what you have to do.</p>
    </div>
    
    <div>
       <a href="register.php">Register</a>
       <a href="login.php">Login</a>
    </div>

</body>
</html>